#!/bin/bash
cd "$(dirname "$0")"/..
export "VERSION=$(grep VERSION ./source/config.h | sed "s/#define VERSION \"//; s/\"//")"
rm -f ./data/acknowledgements.json
make clean
cd app
rm -rfv dist LibreShop_v*
mkdir -pv dist/libreshop

echo -e "\n======== creating source distribution ========"

cd ..
zip -r ./app/dist/src.zip . -x ".git/*" "app/dist/*"


./data/create_acknowledgements "$VERSION"
make

cd app
cp -v ../libreshop_client2.dol dist/libreshop/boot.dol
cp -v ../data/default_config.json dist/libreshop/config.json
sed "s/\$VERSION/${VERSION}/g; s/\$RELEASE/$(date +%Y%m%d%H%M%S)/g" ./meta.xml > dist/libreshop/meta.xml
cp -v ./icon.png dist/libreshop/icon.png

cd dist
unzip src.zip -d libreshop_client2
rm -v src.zip
echo -e "LibreShop v${VERSION} source distribution\n\nPlease read the README.md for compilation instructions." | zip -z -r "./libreshop/GPL_Source_${VERSION}.zip" libreshop_client2
rm -rfv libreshop_client2

zip -r "../LibreShop_v${VERSION}.zip" .
cd ..
rm -rfv dist
rm -f ../data/acknowledgements.json
