#!/bin/bash
cd "$(dirname "$0")"/..
make clean
make
cd app
rm -rfv dist LibreShop\ v*
mkdir -v dist
mkdir -pv dist/libreshop

cp -v ../libreshop_client2.dol dist/libreshop/boot.dol
cp -v ../data/default_config.json dist/libreshop/config.json
cp -v ./meta.xml dist/libreshop/meta.xml
cp -v ./icon.png dist/libreshop/icon.png

cd dist
zip -r "../LibreShop_v$(grep VERSION ../../source/config.h | sed "s/#define VERSION \"//; s/\"//").zip" .
cd ..
rm -rfv dist
