#!/bin/bash

cd "$(dirname "$0")"
export "LINE=============================================================================="

# ========================================================================= #
IFS= read -d "" acknowledgements << EOF
     Hi... The settings aren't implemented yet. Please come back later.
     (When the software updates, preferably.)

     In the meantime, if you need to change repositories, please modify
     the config.json file in the /apps/libreshop directory.

     
EOF

#export "acknowledgements+=
#
#appended"

# wrap it for the Wii
echo -n > acknowledgements.json
echo "acknowledgements.json"
echo "+-----------------------------------------------------------------------------+"
while IFS= read -r p; do
    printf "|%-77s|\n" "${p}"
    printf "%-77s" "${p}" >> acknowledgements.json
done <<< "${acknowledgements}"
echo "+-----------------------------------------------------------------------------+"
